add `CoefficientsOfMorphism` to the categorical-methods record
homalg-project/CAP_project pull request #1132
Opened 2022-11-02 17:47 UTC by kamalsaleh

instead of `CoefficientsOfMorphismWithGivenBasisOfExternalHom`, and support `CoefficientsOfMorphismWithGivenBasisOfExternalHom` as a GAP method until `30.10.2023`.

why? the basis of external-hom is simply dropped in all installations of `CoefficientsOfMorphismWithGivenBasisOfExternalHom` previous to this commit causing unjustified inefficiency.

2022-11-02 20:18 UTC, zickgraf approved these changes
Looks good :-) Only two small things (and, again, a rebase, sorry).

2022-11-02 20:18 UTC, zickgraf commented on LinearAlgebraForCAP/gap/DerivedMethodsForMatrixCategories.gi
> +                      [ BasisOfExternalHom, 1 ], # part of CoefficientsOfMorphism
```suggestion
                      [ BasisOfExternalHom, 1 ],
```
The comment does not apply anymore.

2022-11-02 20:18 UTC, zickgraf commented on CAP/gap/DerivedMethods.gi
> +
Did you add this line deliberately?

2022-11-02 22:11 UTC, kamalsaleh commented on LinearAlgebraForCAP/gap/DerivedMethodsForMatrixCategories.gi
> +                      [ BasisOfExternalHom, 1 ], # part of CoefficientsOfMorphism
True!

2022-11-02 22:11 UTC, kamalsaleh commented on CAP/gap/DerivedMethods.gi
> +
Nope!

2022-11-03 06:47 UTC, zickgraf requested changes

2022-11-03 06:47 UTC, zickgraf commented on FreydCategoriesForCAP/PackageInfo.g
> +  GAP := ">= 4.11.1",
```suggestion
  GAP := ">= 4.12.1",
```

2022-11-03 09:43 UTC, kamalsaleh commented on FreydCategoriesForCAP/PackageInfo.g
> +  GAP := ">= 4.11.1",
Oops, corrected!

2022-11-03 09:58 UTC, zickgraf approved these changes

2022-11-03 09:58 UTC, merged