Category as first argument for `GeneralizedMorphismCategoryByCospans`
homalg-project/CAP_project pull request #1384
Opened 2023-07-17 18:25 UTC by TKuh

Part of #973.

2023-07-18 09:18 UTC, zickgraf requested changes
Thanks! One small change request below, and a general comment in case you are not aware: setting `category_as_first_argument` is completely independent of calling categorical operations with the category as first argument, i.e. it would be enough to simply add a new argument to the functions added via `Add...` without modifying their body. Of course calling categorical operations with the category as first argument is also nice especially if we want to compile the code in the future. But I expect that to take much more time

2023-07-18 12:41 UTC, TKuh commented
> setting `category_as_first_argument` is completely independent of calling categorical operations with the category as first argument, i.e. it would be enough to simply add a new argument to the functions added via `Add...` without modifying their body. 

Thanks for the clarification. I suspected it but wasn't 100% sure. :)

> Of course calling categorical operations with the category as first argument is also nice especially if we want to compile the code in the future. But I expect that to take much more time

My reasoning was, that in this case it's fine because of issue #941. But I will not spend my time on these things in the future then, unless something has to be compilable eventually.

2023-07-18 12:44 UTC, TKuh commented on GeneralizedMorphismsForCAP/gap/GeneralizedMorphismCategoryByCospans.gi
> -    AddIsEqualForCacheForObjects( category, IsIdenticalObj );
Done, thanks for the explanation.

2023-07-19 07:41 UTC, zickgraf approved these changes
Thanks!

2023-07-19 07:41 UTC, zickgraf commented
> > Of course calling categorical operations with the category as first argument is also nice especially if we want to compile the code in the future. But I expect that to take much more time
> 
> My reasoning was, that in this case it's fine because of issue #941. But I will not spend my time on these things in the future then, unless something has to be compilable eventually.

I agree!

2023-07-19 07:42 UTC, merged