turned (InverseOf)MorphismFromCoimageToImage into CAP operations
homalg-project/CAP_project pull request #1485
Opened 2023-10-05 14:11 UTC by mohamed-barakat

2023-10-05 14:35 UTC, zickgraf requested changes

2023-10-05 14:44 UTC, mohamed-barakat commented on CAP/gap/MethodRecord.gi
> +  dual_arguments_reversed := true,
What is superfluous? `dual_arguments_reversed := true`?

2023-10-05 14:45 UTC, mohamed-barakat commented on CAP/gap/MethodRecord.gi
> +  dual_arguments_reversed := true,
Done.

2023-10-05 14:46 UTC, mohamed-barakat commented
Please do not merge until https://github.com/homalg-project/CategoricalTowers/pull/382 is merged.

2023-10-05 17:02 UTC, mohamed-barakat commented
> Please do not merge until [homalg-project/CategoricalTowers#382](https://github.com/homalg-project/CategoricalTowers/pull/382) is merged.

Can be merged now if no further changes are required.

2023-10-05 23:48 UTC, mohamed-barakat commented
Again, please do not merge until https://github.com/homalg-project/CategoricalTowers/pull/383 is merged.

2023-10-06 06:48 UTC, zickgraf submitted a review, later dismissed

2023-10-06 06:48 UTC, zickgraf commented
Thanks, you can merge when it suits CategoricalTowers.

2023-10-06 07:33 UTC, mohamed-barakat commented
> Thanks, you can merge when it suits CategoricalTowers.

Thanks for the approval. I cannot merge without changing the policy since the requirement codecov/project failed. Could you merge, please?

2023-10-06 07:36 UTC, zickgraf commented
Codecov is not an issue, it's the conversations not marked as resolved:

> 2 conversations must be resolved before merging.

However, I just noticed that you have put the non-WithGiven operations below the WithGiven. We usually do it the other way round. Can you swap them?

2023-10-06 07:41 UTC, mohamed-barakat commented
> However, I just noticed that you have put the non-WithGiven operations below the WithGiven. We usually do it the other way round. Can you swap them?

Done.

2023-10-06 07:43 UTC, zickgraf commented on CAP/gap/MethodRecord.gi
> +  dual_arguments_reversed := true,
Somehow `dual_arguments_reversed` has appeared again here and is missing now below.

2023-10-06 07:49 UTC, mohamed-barakat commented on CAP/gap/MethodRecord.gi
> +  dual_arguments_reversed := true,
Yes, just spotted the asymmetry after force pushing. Awkward. Fixed now.

2023-10-06 07:53 UTC, zickgraf approved these changes

2023-10-06 11:48 UTC, merged