converted Display -> DisplayString for AdditiveClosure
homalg-project/CAP_project pull request #1706
Opened 2024-10-29 14:17 UTC by mohamed-barakat

2024-10-29 16:26 UTC, zickgraf commented
@mohamed-barakat It seems like you have accidentally closed this PR. I will reopen it.

2024-10-30 07:39 UTC, zickgraf requested changes
Could you `Display` one of the objects in `AdditiveClosureMonoidal.g`? Then the patch would be fully covered :-)

2024-10-30 21:15 UTC, mohamed-barakat commented
> Could you `Display` one of the objects in `AdditiveClosureMonoidal.g`? Then the patch would be fully covered :-)

Done.

2024-10-31 08:20 UTC, zickgraf approved these changes

2024-10-31 08:20 UTC, merged