Add final derivation for homomorphism structure using BasisOfExternalHom & CoefficientsOfMorphism
homalg-project/CAP_project pull request #645
Opened 2021-03-06 14:27 UTC by kamalsaleh

This PR could be considered as enhancement of https://github.com/homalg-project/CAP_project/pull/457/

Use case : Let R be a commutative ring, and let `grows = CategoryOfGradedRows( R[x,y,z] )` . If `grows` can compute `BasisOfExternalHom` and `CoefficientsOfMorphism`, then `grows` can be equipped with a `Rows(R)`-homomorphism structure.
This will also equip the Freyd category `A(grows)` with a `A(rows(R))`-homomorphism structure.

This PR will make the file `LinearAlgebraForCAP/gap/DerivedMethodsForMatrixCategories.gi` absolete.

2022-11-03 16:20 UTC, zickgraf requested changes
Nice! Some small suggestions below.

2022-11-03 16:20 UTC, zickgraf commented on FreydCategoriesForCAP/gap/CategoryOfRows.gi
> +    return CategoryOfRowsMorphism( hom_source, m, hom_range );
```suggestion
    return CategoryOfRowsMorphism( RangeCategoryOfHomomorphismStructure( cat ), hom_source, m, hom_range );
```

2022-11-03 16:20 UTC, zickgraf commented on FreydCategoriesForCAP/gap/CategoryOfRows.gi
> +    return CategoryOfRowsMorphism( distinguished_object, coeffs, CategoryOfRowsObject( range_cat, NrCols( coeffs ) ) );
```suggestion
    return CategoryOfRowsMorphism( RangeCategoryOfHomomorphismStructure( cat ), distinguished_object, coeffs, CategoryOfRowsObject( range_cat, NrCols( coeffs ) ) );
```

2022-11-03 16:20 UTC, zickgraf commented on FreydCategoriesForCAP/gap/CategoryOfRows.gi
> +    return CategoryOfRowsMorphism( distinguished_object, coeffs, CategoryOfRowsObject( range_cat, NrCols( coeffs ) ) );
Also, please use the WithGiven version to avoid having to construct source and range.

2022-11-03 16:20 UTC, zickgraf commented on FreydCategoriesForCAP/gap/CategoryOfRows.gi
> +  Description := "Using BasisOfExternalHom and CoefficientsOfMorphism to equipp k-linear categories with a Hom-Structure over the category of k-rows"
```suggestion
  Description := "Using BasisOfExternalHom and CoefficientsOfMorphism to equip k-linear categories with a Hom-Structure over the category of k-rows"
```

2022-11-04 15:04 UTC, zickgraf commented
Codecov seems to be completely broken, probably due to the age of this PR. Could you rebase and open a new PR? Sorry :/

2022-11-04 15:14 UTC, kamalsaleh commented
Suppressed by https://github.com/homalg-project/CAP_project/pull/1141

2022-11-04 15:14 UTC, closed without merging