enhanced method record entries
homalg-project/CAP_project pull request #814
Opened 2022-01-26 09:57 UTC by mohamed-barakat

2022-01-26 09:59 UTC, zickgraf requested changes

2022-01-26 09:59 UTC, zickgraf commented on MonoidalCategories/gap/ClosedMonoidalCategoriesMethodRecord.gi
> +  with_given_object_position := "both",
This line will probably cause errors.

2022-01-26 09:59 UTC, zickgraf commented on MonoidalCategories/gap/CoclosedMonoidalCategoriesMethodRecord.gi
> +  with_given_object_position := "both",
This line too.

2022-01-26 10:09 UTC, mohamed-barakat commented on MonoidalCategories/gap/ClosedMonoidalCategoriesMethodRecord.gi
> +  with_given_object_position := "both",
Yes, it did :)

2022-01-26 16:09 UTC, zickgraf requested changes
Is there a reason why you have not touched `IsomorphismFromInternalHomToDual` and `IsomorphismFromCoDualToInternalCoHom`? I think those should also be changed for consistency.

2022-06-11 15:44 UTC, TKuh commented
Since we need to work anyway on the isomorphisms because of #929, what is the status here?

2022-06-28 07:38 UTC, zickgraf commented
@mohamed-barakat Since you are the original author of the PR and since you have originally requested a review from me, I will now merge this.

2022-06-28 07:38 UTC, merged