Fix inconsistent final derivations in rigid monoidal categories
homalg-project/CAP_project pull request #930
Opened 2022-06-11 15:41 UTC by TKuh

Hopefully fixes #929.

I also added remarks about duals in the rigid case and documented the GAP property, which was somehow missing.

2022-06-13 08:31 UTC, zickgraf requested changes

2022-06-13 08:31 UTC, zickgraf commented on MonoidalCategories/gap/RigidSymmetricClosedMonoidalCategoriesDerivedMethods.gi
> +    Description := "adding the isomorphisms between the internal hom and the tensor product as identities"
```suggestion
    Description := "setting the isomorphisms between the internal hom and the tensor product with the dual object to the identities"
```

2022-06-13 08:31 UTC, zickgraf commented on MonoidalCategories/gap/RigidSymmetricCoclosedMonoidalCategoriesDerivedMethods.gi
> +    Description := "adding the isomorphisms between the internal cohom and the tensor product as identities"
see above

2022-06-13 12:11 UTC, TKuh commented on MonoidalCategories/doc/Doc.autodoc
> +The dual objects are given by $\mathrm{\underline{Hom}}(a,1) = a^\vee \otimes 1$
I added a similar comment for (co)closed monoidal.

2022-06-13 12:40 UTC, zickgraf commented on MonoidalCategories/doc/Doc.autodoc
> +If no operations involving coduals are installed manually, the codual objects will be derived as $\mathrm{\underline{coHom}}(1,a) = a_\vee$
```suggestion
If no operations involving coduals are installed manually, the codual objects will be derived as $a_\vee \coloneqq \mathrm{\underline{coHom}}(1,a)$.
```

2022-06-13 12:57 UTC, zickgraf commented on MonoidalCategories/doc/Doc.autodoc
> +If no operations involving duals are installed manually, the dual objects will be derived as $\mathrm{\underline{Hom}}(a,1) = a^\vee \otimes 1$
I guess there are LaTeX-errors in the output of `make doc`? If yes, we have to add `\usepakage{mathtools}` in the `LateExtraPreamble` in `makedoc.g` (for an example see FinGSetsForCAP).

2022-06-13 13:04 UTC, TKuh commented on MonoidalCategories/doc/Doc.autodoc
> +If no operations involving duals are installed manually, the dual objects will be derived as $\mathrm{\underline{Hom}}(a,1) = a^\vee \otimes 1$
Thank you, that did the trick. :)

2022-06-13 14:50 UTC, zickgraf commented on MonoidalCategories/doc/Doc.autodoc
> +If no operations involving duals are installed manually, the dual objects will be derived as $\mathrm{\underline{Hom}}(a,1) = a^\vee \otimes 1$
Have you changed "\coloneqq" to ":=" deliberately?

2022-06-13 22:26 UTC, TKuh commented on MonoidalCategories/doc/Doc.autodoc
> +If no operations involving duals are installed manually, the dual objects will be derived as $\mathrm{\underline{Hom}}(a,1) = a^\vee \otimes 1$
I wanted to change it temporarily to ':=' to see how it looks and forgot to change it back... ugh. I'm sorry.

2022-06-14 07:42 UTC, zickgraf requested changes

2022-06-14 09:54 UTC, TKuh commented on MonoidalCategories/gap/RigidSymmetricClosedMonoidalCategoriesDerivedMethods.gi
> +    return IdentityMorphism( cat, TensorProductOnObjects( cat, DualOnObjects( cat, object ), TensorUnit( cat ) ) );
I think you are right. And having documented this is really helpful for correcting.

2022-06-14 11:24 UTC, zickgraf approved these changes
perfect, now also the diff in the compiled code is gone (up to the weights), which I think is a good sign :-)

2022-06-14 11:25 UTC, merged