CapJitAddTypeSignature in WrapperCategory
homalg-project/CAP_project pull request #958
Opened 2022-07-21 10:46 UTC by mohamed-barakat

for
* UnderlyingCell
* AsObjectInWrapperCategory
* AsMorphismInWrapperCategory

2022-07-28 12:42 UTC, zickgraf requested changes
Please use the new helper functions

* CapJitDataTypeOfCategory,
* CapJitDataTypeOfObjectCategory,
* CapJitDataTypeOfMorphismOfCategory.

For an example see OppositeCategory.

2022-07-28 14:15 UTC, mohamed-barakat commented
> Please use the new helper functions
> 
> * CapJitDataTypeOfCategory,

I don't see where to use this one, probably you listed it for the sake of completeness.

> * CapJitDataTypeOfObjectCategory,
> * CapJitDataTypeOfMorphismOfCategory.

Done.

> For an example see OppositeCategory.

Thanks.

2022-07-28 14:18 UTC, zickgraf requested changes
> I don't see where to use this one, probably you listed it for the sake of completeness.

Exactly, I did not think about the details here :D

2022-07-28 14:18 UTC, zickgraf commented on CAP/gap/WrapperCategory.gd
> +    return CapJitDataTypeOfObjectOfCategory( ModelingCategory( input_types[1].category ) );
```suggestion
    return CapJitDataTypeOfObjectOfCategory( ModelingCategory( input_types[1].category ) );
    
```
(missing empty line)

2022-07-28 14:18 UTC, zickgraf commented on CAP/gap/WrapperCategory.gd
> +    return CapJitDataTypeOfMorphismOfCategory( ModelingCategory( input_types[1].category ) );
```suggestion
    return CapJitDataTypeOfMorphismOfCategory( ModelingCategory( input_types[1].category ) );
    
```
(missing empty line)

2022-08-05 13:05 UTC, mohamed-barakat commented on CAP/gap/WrapperCategory.gd
> +    return CapJitDataTypeOfObjectOfCategory( ModelingCategory( input_types[1].category ) );
Done.

2022-08-05 13:05 UTC, mohamed-barakat commented on CAP/gap/WrapperCategory.gd
> +    return CapJitDataTypeOfMorphismOfCategory( ModelingCategory( input_types[1].category ) );
Done.

2022-08-08 11:28 UTC, zickgraf requested changes

2022-08-08 11:28 UTC, zickgraf commented on CAP/gap/WrapperCategory.gd
> +        [ IsCapCategory, IsCapCategoryObject ],
```suggestion
        [ IsWrapperCapCategory, IsCapCategoryObject ],
```

2022-08-08 11:28 UTC, zickgraf commented on CAP/gap/WrapperCategory.gd
> +        [ IsCapCategory, IsWrapperCapCategoryObject, IsCapCategoryMorphism, IsWrapperCapCategoryObject ],
```suggestion
        [ IsWrapperCapCategory, IsWrapperCapCategoryObject, IsCapCategoryMorphism, IsWrapperCapCategoryObject ],
```

2022-08-08 11:35 UTC, mohamed-barakat commented on CAP/gap/WrapperCategory.gd
> +        [ IsCapCategory, IsCapCategoryObject ],
Done.

2022-08-08 11:35 UTC, mohamed-barakat commented on CAP/gap/WrapperCategory.gd
> +        [ IsCapCategory, IsWrapperCapCategoryObject, IsCapCategoryMorphism, IsWrapperCapCategoryObject ],
Done.

2022-08-08 11:38 UTC, zickgraf approved these changes

2022-08-08 12:20 UTC, merged